### ISSUE TITLE
Question: Docs of API endpoints

### ISSUE THREAD

**Issue by boinappi** [gimelli-engineering-ag/js-readout#1]
Thank you for sharing this code! This is extremely useful!
You are fetching data from:
`https://${robot.ip}/desk/api/robot/configuration`

But according to the RobotState docs there is more. I wonder if there are docs for the API endpoints to get a more profound dataset of the robot. I was searching everywhere on the franka pages, but could not find an endpoint doc.

Thanks for sharing!

**Comment by Pascal-So** [comment]
Hi, I'm glad that the code is useful to you!

Unfortunately we cannot provide any official documentation for this API. We only found this URL through reverse-engineering, and we believe that the reason that Franka doesn't publish a documentation is that the API is not intended for use by other components and might change in a non-backwards-compatible way at any time without warning.
